--- 
title: "Case Study 1"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# github-repo: (your-github-repository)
description: "Google Data Analyticsのケーススタディ1"
---

# Aks(課題の明確化)
## 状況整理(与えられた資料より)
2016年、サイクリスティックは自転車シェアサービスを開始し、成功を収めた。それ以来、このプログラムは5,824台の自転車を保有するまでに成長した。
シカゴ全土に692カ所あるステーションネットワークにジオトラッキングされ、ロックされている。自転車は1つのステーションから鍵を開け、システム内の他のステーションに戻すことができる。
いつでも他のステーションに戻すことができる。


これまで、サイクリスティックのマーケティング戦略は、一般的な認知度を高め、幅広い消費者層にアピールすることに依存していた。
これらを可能にしたアプローチのひとつが、シングルライド・パス、1日パス、年会費といった料金プランの柔軟性だ、
そして年間会員権である。一日乗車券や一日乗車券を購入する顧客は、カジュアル・ライダーと呼ばれる。年間会員
年会費を購入する顧客はサイクリスティック・メンバーである。


サイクリスティックの財務アナリストは、カジュアルライダーよりも年間会員の方がはるかに収益性が高いと結論付けている。価格設定の柔軟性はサイクリスティックがより多くの顧客を獲得するのに役立つが、モレノは年間会員数を最大化することが今後の成長の鍵になると考えている。モレノは、新規顧客をターゲットにしたマーケティング・キャンペーンを行うよりも、カジュアル・ライダーを会員に変えるチャンスが非常に大きいと考えている。彼女は、カジュアルライダーはすでにサイクリスティックのプログラムを知っており、移動のニーズに合わせてサイクリスティックを選んでいると指摘する。


モレノは明確な目標を設定した。カジュアルライダーを年間会員に変えることを目的としたマーケティング戦略を立案することだ。しかし、そのためには、年間会員とカジュアルライダーの違い、カジュアルライダーが会員権を購入する理由、デジタルメディアがマーケティング戦術に与える影響などを、マーケティング・アナリストチームがよりよく理解する必要がある。モレノと彼女のチームは、サイクリスティックの過去の自転車旅行データを分析して傾向を特定することに興味を持っている。


## ステークホルダー
- Lily Moreno(上司)
- Cyclistic marketing analytics team(分析チーム)
- Cyclistic exective team(経営陣)

## ビジネスの課題
- 会社の収益を上げること。できれるだけ、カジュアルライダーを年間会員にすること。

### 分析のための問い
1. 年間会員(member)とカジュアルライダー(casual)は、Cyclisticバイクをどのように使い分けているのですか？
2. なぜカジュアルライダー(casual)はサイクリスティックの年会費を買うのか？
3. サイクリスティックはデジタル・メディアを利用して、カジュアルライダー(casual)にどのような影響を与え、会員になってもらうことができるのか？
